modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
    modId = "simplehomes"
    version = "1.1.0"
    displayName = "SimpleHomes"
    updateJSONURL = "https://minecraft.darkboy.ru/api/check-mod-updates/simplehomes.json"
    displayURL = "https://minecraft.darkboy.ru/mods/simplehomes"
    credits = "Simple: homes"
    authors = "Bobsans"
    description = '''Lost in cave? /home sloves you problemn'''

    [[dependencies.simplehomes]]
        modId = "forge"
        mandatory = true
        versionRange = "[36,)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.simplehomes]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[1.16.5,1.17)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.simplehomes]]
        modId = "boblib"
        mandatory = true
        versionRange = "[0.2.0,)"
        ordering = "NONE"
        side = "BOTH"
