modLoader = "javafml"
loaderVersion = "[44,)"
license = "All rights reserved"

[[mods]]
    modId = "simplehomes"
    version = "1.2.2"
    displayName = "SimpleHomes"
    updateJSONURL = "https://minecraft.darkboy.ru/api/check-mod-updates/simplehomes.json"
    displayURL = "https://minecraft.darkboy.ru/mods/simplehomes"
    credits = "Simple: homes"
    authors = "Bobsans"
    description = '''Lost in cave? /home sloves you problemn'''

    [[dependencies.simplehomes]]
        modId = "forge"
        mandatory = true
        versionRange = "[44,)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.simplehomes]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[1.19.3,1.20)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.simplehomes]]
        modId = "boblib"
        mandatory = true
        versionRange = "[0.3.1,)"
        ordering = "NONE"
        side = "BOTH"
