modLoader="javafml"
loaderVersion="${forge_version_map}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="${mod_update_url}"
    displayURL="${mod_url}"
    credits="${mod_credits}"
    authors="${mod_author}"
    description='''${mod_description}'''

    [[dependencies.simplehomes]]
        modId="forge"
        mandatory=true
        versionRange="${forge_version_map}"
        ordering="NONE"
        side="BOTH"

    [[dependencies.simplehomes]]
        modId="minecraft"
        mandatory=true
        versionRange="${minecraft_version_map}"
        ordering="NONE"
        side="BOTH"

    [[dependencies.simplehomes]]
        modId="boblib"
        mandatory=true
        versionRange="${boblib_version_map}"
        ordering="AFTER"
        side="BOTH"
